export const AchievementsDB = [
    {
        name: "Azure Fundamentals",
        Title: "Certificate",
        otorged_by: "Microsoft",
        logo: "../assets/achievements-icon/microsoft-certified-fundamentals-badge.svg",
        image: "../assets/achievements/Azure_Fundamentals.jpg",
    },
    {
        name: "New Relic: Full Stack Observability",
        Title: "Certificate",
        otorged_by: "New Relic University",
        logo: "../assets/achievements-icon/new-relic.png",
        image: "../assets/achievements/Full_Stack_Obserbavility.jpg",
    },
    {
        name: "HTML y CSS a Profundidad",
        Title: "Diploma",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/Escuela-Desarrollo-Web.webp",
        image: "../assets/achievements/Platzi-Diploma_HTML_y_CSS_a_Profundidad.jpg",
    },
    {
        name: "JavaScript a Profundidad",
        Title: "Diploma",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/JavaScriptaProfundidad.webp",
        image: "../assets/achievements/Platzi-Diploma_JavaScrip_a_Profundidad.jpg",
    },
    {
        name: "Full Stack Developer con JavaScript",
        Title: "Diploma",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/JavaScriptaProfundidad.webp",
        image: "../assets/achievements/Diploma-FullStackDeveloper-con-JavaScript.png",
    },
    {
        name: "EF SET Certificate",
        Title: "Certificate",
        otorged_by: "EF SET",
        logo: "../assets/achievements-icon/EFSET-C1.png",
        image: "../assets/achievements/EFSETCertificate.png",
    },
    {
        name: "Administracion de Servidores Linux",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/servidores-linux.webp",
        image: "../assets/achievements/Administracion-de-Servidores-Linux.jpg",
    },
    {
        name: "Animaciones con CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-animacion-css.webp",
        image: "../assets/achievements/Animaciones-con-CSS.jpg",
    },
    {
        name: "Asincronismo con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-asincro-js.png",
        image: "../assets/achievements/Asincronismo-con-JavaScript.jpg",
    },
    {
        name: "Backend con Node.JS - API REST con Express.JS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-backend-nodejs-apirest-expressjs.png",
        image: "../assets/achievements/Backend-con-Node.JS-API-REST-con-Express.JS.jpg",
    },
    {
        name: "Backend con Node.JS - Bases de Datos con PostgresSQL",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/backend-node.png",
        image: "../assets/achievements/Backend-con-Node.JS-Bases-de-Datos-con-PostgresSQL.jpg",
    },
    {
        name: "Backend con Node.JS - Autenticación con PassportJS y JWT",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-backend-nodejs-autenticacion-passportjs-jwt.png",
        image: "../assets/achievements/Backend-con-NodeJS-Autenticacion-con-PassportJS-y-JWT.png",
    },
    {
        name: "Basico de Javascript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-basicojs.png",
        image: "../assets/achievements/Basico-de-Javascript.jpg",
    },
    {
        name: "Clean Code con JabaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-clean-code-javascript.webp",
        image: "../assets/achievements/CleanCode-en-JavaScript.png",
    },
    {
        name: "Basico de TailwindCSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-basico-tailwind_badge.png",
        image: "../assets/achievements/Basico-de-TailwindCSS.jpg",
    },
    {
        name: "Closure y Scope en JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-piezas-clousures-scope-javascript.webp",
        image: "../assets/achievements/Closure-y-Scope-en-JavaScript.jpg",
    },
    {
        name: "Complejidad Algoritmica con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-complejidad-algoritmica-js.png",
        image: "../assets/achievements/Complejidad-Algoritmica-con-JavaScript.jpg",
    },
    {
        name: "Computacion Basica",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-computacion-basica.png",
        image: "../assets/achievements/Computacion-Basica.jpg",
    },
    {
        name: "Consumo de API REST con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/API-REST-js.webp",
        image: "../assets/achievements/Consumo-de-API-REST-con-JavaScript.jpg",
    },
    {
        name: "CSS Grid Basico",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-css-grid-basico.png",
        image: "../assets/achievements/CSS-Grid-Basico.jpg",
    },
    {
        name: "Conseguir Trabajo como Frontend Developer",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/conseguir-trabajo-frontend-developer-badge.png",
        image: "../assets/achievements/Curso-para-Conseguir-Trabajo-como-Frontend-Developer.jpg",
    },
    {
        name: "Debugging con Chrome DevTools",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-debugging-chrome-devtools.webp",
        image: "../assets/achievements/Debugging-con-Chrome-DevTools.jpg",
    },
    {
        name: "Diseño para Programadores",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-diseno-para-programadores.webp",
        image: "../assets/achievements/Diseño-para-Programadores.jpg",
    },
    {
        name: "Diseño Web con CSS Grid y Flexbox",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-diseno-cssgrid-flexbox.png",
        image: "../assets/achievements/Diseño-Web-con-CSS-Grid-y-Flexbox.jpg",
    },
    {
        name: "Docker",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/docker.png",
        image: "../assets/achievements/Docker.jpg",
    },
    {
        name: "ECMAScript - Historia y Versiones de JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-escmascript-historia.png",
        image: "../assets/achievements/ECMAScript-HistoriaVersionesJavaScript.jpg",
    },
    {
        name: "Introduccion a la Web: historia y Funcionamiento de Internet",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-introduccion-web-historia-internet.webp",
        image: "../assets/achievements/Introduccion-a-la-Web-Historia-y-funcionamienro-del-internet.jpg",
    },
    {
        name: "Inteligencia Artifical con ChatGPT, Dall-E y Hugging Faces",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badgeintro-ia.png",
        image: "../assets/achievements/Inteligencia-Artificial-con-ChatGPT,Dall-E-y-Hugging-Faces.png",
    },
    {
        name: "Esctructura de Datos con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/estructura-datos-javascript.png",
        image: "../assets/achievements/Esctructura-de-Datos-con-JavaScript.jpg",
    },
    {
        name: "Flujo de Desarrollo Moderno Codestream",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/flujo-desarrollo-codestream.webp",
        image: "../assets/achievements/Flujo-de-Desarrollo-Moderno-Codestream.jpg",
    },
    {
        name: "Framework y Librerias de JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-introduccion-frameworks-javascript.png",
        image: "../assets/achievements/Framework-y-Librerias-de-JavaScript.jpg",
    },
    {
        name: "Frontend Developer",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-curso-frontend-developer.png",
        image: "../assets/achievements/Frontend-Developer.jpg",
    },
    {
        name: "Fundamentos de Bases de Datos",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/fundamentos-de-bases-de-datos.webp",
        image: "../assets/achievements/Fundamentos-de-Bases-de-Datos.jpg",
    },
    {
        name: "Fundamentos de Ingeniria de Software",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/ing-software.webp",
        image: "../assets/achievements/Fundamentos-de-Ingeniria-de-Software.jpg",
    },
    {
        name: "Fundamentos de Node.JS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-fundamentos-nodejs.png",
        image: "../assets/achievements/Fundamentos-de-Node.JS.jpg",
    },
    {
        name: "Definitivo de HTML y CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-html-css.webp",
        image: "../assets/achievements/",
    },
    {
        name: "Inroduccion a ReactJS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-react.png          ",
        image: "../assets/achievements/Inroduccion-a-ReactJS.jpg",
    },
    {
        name: "Intermedio de Programacion Orientada a Objetos con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/intermedio-programacion-orientada-js-badge.png",
        image: "../assets/achievements/Intermedio-de-Programacion-Orientada-a-Objetos-con-JavaScript.jpg",
    },
    {
        name: "Introduccion a la nube con AZURE",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/introduccion-nube-azure.png",
        image: "../assets/achievements/Introduccion-a-la-nube-con-AZURE.jpg",
    },
    {
        name: "Introduccion al Desarrollo Backend",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-intro-backend-developer.png",
        image: "../assets/achievements/Introduccion-al-Desarrollo-Backend.jpg",
    },
    {
        name: "Introduccion a la terminal y linea de comandos",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-terminal.webp",
        image: "../assets/achievements/Itroduccion-a-la-terminal-y-linea-de-comandos.jpg",
    },
    {
        name: "JavaScript Engine (V8) y el Navegador",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-javascript-engine-v8-navegador.webp",
        image: "../assets/achievements/JavaScript-Engine(V8)-y-el-Navegador.jpg",
    },
    {
        name: "Laboratorio de JavaScript FakeStore",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-laboratorio-javascript-fake-store-copy_badge.webp",
        image: "../assets/achievements/Laboratorio-de-JavaScript-FakeStore.jpg",
    },
    {
        name: "Laboratorio Profesional de JavaScript - Prueba Tecnica",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-laboratorio-profesional-javascript-prueba-tecnica_badge.webp",
        image: "../assets/achievements/Laboratorio-Profesional-de-JavaScript-Prueba-Tecnica.jpg",
    },
    {
        name: "Manipulacion de Arrays en JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-arrays-javascript_badge.webp",
        image: "../assets/achievements/Manipulacion-de-Arrays-en-JavaScript.jpg",
    },
    {
        name: "New Relic - Observabilidad, Monitoreo y Performance Web",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/New Relic-Observabilidad,-Monitoreo-y-PerformanceWeb.webp",
        image: "../assets/achievements/New Relic-Observabilidad,-Monitoreo-y-PerformanceWeb.jpg",
    },
    {
        name: "NPM - Gestion de Paquetes y Dependencias en JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-npm-js.png",
        image: "../assets/achievements/NPM-Gestion-de-Paquetes-y-Dependencias-en-JavaScript.jpg",
    },
    {
        name: "Organización y Productividad con Notion",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-notion-nuevo.webp",
        image: "../assets/achievements/Organización-y-Productividad-con-Notion.jpg",
    },
    {
        name: "Pensamiento Logico - Algoritmos y Diagramas de Flujo",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas_pensamiento-logico-algoritmos-diagramas-flujo.webp",
        image: "../assets/achievements/Pensamiento-Logico-Algoritmos-y-Diagramas-de-Flujo.jpg",
    },
    {
        name: "Pensamiento Logico - Funciones y Estructuras de Control",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas_pensamiento-logico-funciones-estructuras-control.webp",
        image: "../assets/achievements/Pensamiento-Logico-FuncionesyEstructuras-de-Control.jpg",
    },
    {
        name: "Pensamiento Logico - Lenguajes de Programacion",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas_pensamiento-lenguajes-programacion.webp",
        image: "../assets/achievements/Pensamiento-Logico-Lenguajes-de-Programacion.jpg",
    },
    {
        name: "Audiocurso de Frameworks y Arquitecturas Frontend - Casos de Estudio.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-frameworks-arquitecturas.png",
        image: "../assets/achievements/Frameworks_y_Arquitecturas_Frontend-Casos-de-Estudio.jpg",
    },
    {
        name: "Practico de Maquetación y Animaciones con CSS.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-practico-animacion-css.png",
        image: "../assets/achievements/Practico-de-Animaciones-con-CSS.jpg",
    },
    {
        name: "Practico de Consumo de API REST con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/practico-API-REST-js.png",
        image: "../assets/achievements/Practico-de-Consumo-de-API-REST-con-JavaScript.jpg",
    },
    {
        name: "Practico de Frontend Developer",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-curso-practico-frontend-developer.png",
        image: "../assets/achievements/Practico-de-Frontend-Developer.jpg",
    },
    {
        name: "Practico de HTML y CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-practico-html-css.png",
        image: "../assets/achievements/Practico-de-HTML-y-CSS.jpg",
    },
    {
        name: "Practico de JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/practico-javascript_badge.webp",
        image: "../assets/achievements/Practico-de-JavaScript.jpg",
    },
    {
        name: "Practico de Maquetacion en CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-css-grid.png",
        image: "../assets/achievements/Practico-de-Maquetacion-en-CSS.jpg",
    },
    {
        name: "Practico de NextJS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-practico-next-js.png",
        image: "../assets/achievements/Practico-de-NextJS.jpg",
    },
    {
        name: "Practico de ReactJS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-reactjs-badge.png",
        image: "../assets/achievements/Practico-de-ReactJS.jpg",
    },
    {
        name: "Preprocesadores CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-preprocesadores.png",
        image: "../assets/achievements/PreprocesadoresCSS.jpg",
    },
    {
        name: "Prework - Configuracion de Entorno de Desarrollo de Windows",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/prework-configuracion-entorno-windows.png",
        image: "../assets/achievements/Prework-Configuracion-de-Entorno-de-Desarrollo-de-Windows.jpg",
    },
    {
        name: "Prework - Configuracion de Entorno de Desarrollo de Windows(Nuevo)",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/prework-configuracion-entorno-windows.png",
        image: "../assets/achievements/Prework-Configuracion-de-Entorno-de-Desarrollo-de-Windows2.png",
    },
    {
        name: "Prework - Configuracion de Entorno de Desarrollo en Linux",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/prework-linux.png",
        image: "../assets/achievements/Prework-Configuracion-de-Entorno-de-Desarrollo-en-Linux.jpg",
    },
    {
        name: "Prework - Configuracion de Entorno de Desarrollo en MacOS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/prework-configuracion-entorno-mac.png",
        image: "../assets/achievements/Prework-Configuracion-de-Entorno-de-Desarrollo-en-MacOS.jpg",
    },
    {
        name: "Profesional de Consumo de API REST con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/curso-profesional-consumo-api-rest-javascript_badge.webp",
        image: "../assets/achievements/Profesional-de-Consumo-de-API-REST-con-JavaScript.jpg",
    },
    {
        name: "Profesional de Git y Github",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-github.webp",
        image: "../assets/achievements/Profesional-de-GIT-y-GITHub.jpg",
    },
    {
        name: "Profesional de CSS Grid Layout.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/css-grid-layout_badge.png",
        image: "../assets/achievements/Profesional-de-CSS-Grid-Layout.jpg",
    },
    {
        name: "Profesional de DevOps",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/devops.png",
        image: "../assets/achievements/Profesional-de-DevOps.jpg",
    },
    {
        name: "Profesional de Next.JS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/piezas-profesional-nextjs_badge.png",
        image: "../assets/achievements/Profesional-de-Next.JS.jpg",
    },
    {
        name: "Programacion Básica",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-piezas-programacion-basica.webp",
        image: "../assets/achievements/Programacion-basica.jpg",
    },
    {
        name: "Programacion Funcional en JS.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-programacion-funcional-js.png",
        image: "../assets/achievements/Programacion-Funcional-en-JS-por-BEDU.jpg",
    },
    {
        name: "Programacion Orientada a Objetos",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-poo.webp",
        image: "../assets/achievements/Programacion-Orientada-a-Objetos.jpg",
    },
    {
        name: "Programacion Orientada a Objetos con JavaScript",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-curso-js-poo.png",
        image: "../assets/achievements/Programacion-Orientada-a-Objetos-con-JavaScript.jpg",
    },
    {
        name: "React.JS Manejo Profesional del Estado",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/react.png",
        image: "../assets/achievements/React.JS-Manejo-Profesional-del-Estado.jpg",
    },
    {
        name: "React.JS Patrones de Render y Composicion",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/reactjs-patrones-render_badge.webp",
        image: "../assets/achievements/React.JS-Patrones-de-Render-y-Composicion.jpg",
    },
    {
        name: "Responsive Design - Maquetacion Mobile First.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-responsive-design.png",
        image: "../assets/achievements/Responsive-Design-MaquetacionMobileFirst.jpg",
    },
    {
        name: "Sistemas de Diseño",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-sistema-diseno.webp",
        image: "../assets/achievements/Sistemas-de-Diseño.jpg",
    },
    {
        name: "Taller de Practico de JavaScript - Matematicas y Estadistica Basica",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/practico-javascript-matematicas_piezas_badge.webp",
        image: "../assets/achievements/Taller-Practico-de-JavaScript-Matematicas-y-Estadistica-Basica.jpg",
    },
    {
        name: "Taller de Practico de JavaScript - Crea tu primer videojuego",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-js-videojuegos-web.png",
        image: "../assets/achievements/Taller-Practico-de-JavaScript-Crea-tu-primer-videojuego.jpg",
    },
    {
        name: "Taller Secretos Ocultos de JavaScript - Proteccion de Objetos",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badgetallerPOO.webp",
        image: "../assets/achievements/Taller-SecretosOcultos-de-Javascript-Proteccion-de-Objetos-para-Misiones-Espaciales.png",
    },
    {
        name: "Trabajo Remoto y Teletrabajo.jpg",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-trabajo-remoto.png",
        image: "../assets/achievements/TrabajoRemotoTeletrabajo.jpg",
    },
    {
        name: "Transformaciones y Transiciones en CSS",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badges-animacion-css.png",
        image: "../assets/achievements/Transformaciones-y-Transiciones-en-CSS.jpg",
    },
    {
        name: "Webpack",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/badge-webpack.webp",
        image: "../assets/achievements/Webpack.jpg",
    },
    {
        name: "State Machines en React.js",
        Title: "Certificate",
        otorged_by: "Platzi",
        logo: "../assets/achievements-icon/staet-machines-badge.webp",
        image: "../assets/achievements/State-Machines-en-React.JS.jpg",
    },
];
