export const portfolioDB = [
        {
            name: "Platzi Movies",
            description: "This project use de MovieDB API to bring us movie trend around the world",
            image: "../assets/portfolio/moviedb.jpg",
            deploy_link: "https://amaneiro7.github.io/MovideDB/",
            repository_link: "https://github.com/amaneiro7/MovideDB",
        },
        {
            name: "Product APP Fazt Tutorial",
            description: "This project was a tutorial from Fazt to create a APP with class in javascript",
            image: "../assets/portfolio/productapp.jpg",
            deploy_link: "https://amaneiro7.github.io/ProductAppFaztTutorial/",
            repository_link: "https://github.com/amaneiro7/ProductAppFaztTutorial",
        },
        {
            name: "Random Profile API Curso Webpack",
            description: "This project is a profile random API, realized to put a practice a webpak configuration",
            image: "../assets/portfolio/webpack.jpg",
            deploy_link: "https://cursowebpackam7.netlify.app/",
            repository_link: "https://github.com/amaneiro7/CursoWebpack",
        },
        {
            name: "CarpiShop - React",
            description: "This is one of my first personal project to create a fake store using React",
            image: "../assets/portfolio/CarpiShop.jpg",
            deploy_link: "https://amaneiro7.github.io/e-commerce-react/",
            repository_link: "https://github.com/amaneiro7/e-commerce-react",
        },
        {
            name: "Batatabit",
            description: "This website was realized in a platzi CSS course",
            image: "../assets/portfolio/batatabit.jpg",
            deploy_link: "https://amaneiro7.github.io/Batatabit/",
            repository_link: "https://github.com/amaneiro7/Batatabit",
        },
        {
            name: "Google Clon",
            description: "This is a clon of google realized width HTML, CSS and vainilla JavaScript",
            image: "../assets/portfolio/clongoogle.jpg",
            deploy_link: "https://amaneiro7.github.io/GoogleClonePlatzi/",
            repository_link: "https://github.com/amaneiro7/GoogleClonePlatzi",
        },
        {
            name: "API youtube",
            description: "This is a project realized in a platzi course, using a youtube api to bring the latest video of a specific channel",
            image: "../assets/portfolio/apiyoutube.jpg",
            deploy_link: "https://amaneiro7.github.io/async-landing/",
            repository_link: "https://github.com/amaneiro7/async-landing/",
        },
        {
            name: "API Weather Fazt Tutorial",
            description: "This is a project with vainilla javascript, using a API that bring us the weather of a specific city adn save de last search in the localstorage",
            image: "../assets/portfolio/apiweather.jpg",
            deploy_link: "https://amaneiro7.github.io/WeatherAPP/",
            repository_link: "https://github.com/amaneiro7/WeatherAPP/",
        },
        {
            name: "ToDo List",
            description: "This project is a challenge from platzi to create a To Do List",
            image: "../assets/portfolio/todo.jpg",
            deploy_link: "https://proyectotodo.netlify.app/",
            repository_link: "https://github.com/amaneiro7/laboratorio-mydayapp-js",
        },
        {
            name: "Advice Generator",
            description: "This is a project from a Frontend Mentor Challenge, using a API to generate a Random Advice",
            image: "../assets/portfolio/advicegenerator.jpg",
            deploy_link: "https://advicegenereatoram7.netlify.app/",
            repository_link: "https://github.com/amaneiro7/-github.com-amaneiro7-AdviceGenerator",
        },
        {
            name: "Platzi FakeStore",
            description: "This project is a challenge from a Platzi to create a small e-commerce",
            image: "../assets/portfolio/fakestore.jpg",
            deploy_link: "https://platzifakestoream7.netlify.app/",
            repository_link: "https://github.com/amaneiro7/laboratorio-fakestore",
        },
        {
            name: "PokeApi",
            description: "This project is a small pokedex using a Pokemon API",
            image: "../assets/portfolio/pokeapi.jpg",
            deploy_link: "https://amaneiro7.github.io/PokeApi01/",
            repository_link: "https://github.com/amaneiro7/PokeApi01",
        },
        {
            name: "Challenge of a Template",
            description: "This is a template of a portfolio web mobile version",
            image: "../assets/portfolio/templateportfolio2.jpg",
            deploy_link: "https://amaneiro7.github.io/UXTemplate/",
            repository_link: "https://github.com/amaneiro7/UXTemplate",
        },
        {
            name: "Challenge of a Template",
            description: "This is a template of a portfolio web",
            image: "../assets/portfolio/templateportfolio.jpg",
            deploy_link: "https://amaneiro7.github.io/HolaJuniorsReto/",
            repository_link: "https://github.com/amaneiro7/HolaJuniorsReto",
        },
        {
            name: "ToDo Machine",
            description: "This is a ToDo Machine realized of react course from platzi",
            image: "../assets/portfolio/todomachine.jpg",
            deploy_link: "https://amaneiro7.github.io/platzitodoreact/",
            repository_link: "https://github.com/amaneiro7/platzitodoreact",
        },
        {
            name: "Platzi VideoGames",
            description: "This is a videogame realized wifth vainilla javascript",
            image: "../assets/portfolio/platzivideogame.jpg",
            deploy_link: "https://amaneiro7.github.io/PlatziVideogame/",
            repository_link: "https://github.com/amaneiro7/PlatziVideogame",
        },
        {
            name: "404 Page Challenge",
            description: "This is a project from a frotend mentor challenge",
            image: "../assets/portfolio/404pagechallenge.jpg",
            deploy_link: " https://amaneiro7.github.io/404PageChallenge/",
            repository_link: "https://github.com/amaneiro7/404PageChallenge",
        },
        {
            name: "Platzi Blog React-Routers-Dom",
            description: "This is a project from a challenge from platzi, to put in practice React-Dom, privite routes, and a fake login",
            image: "../assets/portfolio/react-dom-platzi-pratice.jpg",
            deploy_link: " https://amaneiro7.github.io/react-dom-platzi-pratice/",
            repository_link: "https://github.com/amaneiro7/react-dom-platzi-pratice",
        },
    ];
